packages:
  - apps/*
  - packages/*
  - services/*

catalog:
  vitest: ^3.1.4
  zod: ^3.25.6
  typescript: ^5.8.3
  tsx: ^4.19.4
  prettier: ^3.5.3
  eslint: ^9.15.0
  '@types/node': ^22.9.0
  dotenv-cli: ^8.0.0
  pino: ^9.7.0
  pino-pretty: ^13.0.0
  '@t3-oss/env-core': ^0.13.4
  '@paralleldrive/cuid2': ^2.2.2
  tailwindcss: ^4
  '@tailwindcss/postcss': ^4
  drizzle-orm: ^0.43.1
  fastify: ^5.4.0
  better-auth: ^1.2.12
  sst: ^3.17.10
