/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    'dev-calmpulse-ai-api': {
      service: string;
      type: 'sst.aws.Service';
      url: string;
    };
    'dev-calmpulse-ai-db': {
      database: string;
      host: string;
      password: string;
      port: number;
      type: 'sst.aws.Postgres';
      username: string;
    };
    'dev-calmpulse-ai-frontend': {
      type: 'sst.aws.Nextjs';
      url: string;
    };
    'dev-calmpulse-ai-vpc': {
      bastion: string;
      type: 'sst.aws.Vpc';
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
