export enum SlackEventTypes {
  MEMBER_JOINED_CHANNEL = 'MEMBER_JOINED_CHANNEL',
  TEAM_JOIN = 'TEAM_JOIN',
  APP_MENTION = 'APP_MENTION',
  MESSAGE = 'MESSAGE',
  USER_CHANGE = 'USER_CHANGE',
  APP_UNINSTALLED = 'APP_UNINSTALLED',
  TOKENS_REVOKED = 'TOKENS_REVOKED',
  DND_UPDATED_USER = 'DND_UPDATED_USER',
  TEAM_RENAME = 'TEAM_RENAME',
  TEAM_DOMAIN_CHANGE = 'TEAM_DOMAIN_CHANGE',
}
